// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// CreateWishlistItemRequest defines model for CreateWishlistItemRequest.
type CreateWishlistItemRequest struct {
	Comment *string  `json:"comment,omitempty"`
	Price   *float64 `json:"price,omitempty"`
	Title   string   `json:"title"`
	Url     *string  `json:"url,omitempty"`
}

// CreateWishlistRequest defines model for CreateWishlistRequest.
type CreateWishlistRequest struct {
	Name  string `json:"name"`
	Owner string `json:"owner"`
}

// Wishlist defines model for Wishlist.
type Wishlist struct {
	Id    int64          `json:"id"`
	Items []WishlistItem `json:"items"`
	Name  string         `json:"name"`
	Owner string         `json:"owner"`
}

// WishlistItem defines model for WishlistItem.
type WishlistItem struct {
	Comment *string  `json:"comment,omitempty"`
	Id      int64    `json:"id"`
	Price   *float64 `json:"price,omitempty"`
	Title   string   `json:"title"`
	Url     *string  `json:"url,omitempty"`
}

// CreateWishlistJSONRequestBody defines body for CreateWishlist for application/json ContentType.
type CreateWishlistJSONRequestBody = CreateWishlistRequest

// AddWishlistItemJSONRequestBody defines body for AddWishlistItem for application/json ContentType.
type AddWishlistItemJSONRequestBody = CreateWishlistItemRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение списка вишлистов
	// (GET /wishlists)
	GetWishlists(w http.ResponseWriter, r *http.Request)
	// Создание нового вишлиста
	// (POST /wishlists)
	CreateWishlist(w http.ResponseWriter, r *http.Request)
	// Удаление вишлиста
	// (DELETE /wishlists/{wishlistId})
	DeleteWishlist(w http.ResponseWriter, r *http.Request, wishlistId int64)
	// Получение вишлиста по id
	// (GET /wishlists/{wishlistId})
	GetWishlistById(w http.ResponseWriter, r *http.Request, wishlistId int64)
	// Добавление элемента в вишлист
	// (POST /wishlists/{wishlistId}/items)
	AddWishlistItem(w http.ResponseWriter, r *http.Request, wishlistId int64)
	// Удаление элемента из вишлиста
	// (DELETE /wishlists/{wishlistId}/items/{itemId})
	DeleteWishlistItem(w http.ResponseWriter, r *http.Request, wishlistId int64, itemId int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получение списка вишлистов
// (GET /wishlists)
func (_ Unimplemented) GetWishlists(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создание нового вишлиста
// (POST /wishlists)
func (_ Unimplemented) CreateWishlist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удаление вишлиста
// (DELETE /wishlists/{wishlistId})
func (_ Unimplemented) DeleteWishlist(w http.ResponseWriter, r *http.Request, wishlistId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение вишлиста по id
// (GET /wishlists/{wishlistId})
func (_ Unimplemented) GetWishlistById(w http.ResponseWriter, r *http.Request, wishlistId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Добавление элемента в вишлист
// (POST /wishlists/{wishlistId}/items)
func (_ Unimplemented) AddWishlistItem(w http.ResponseWriter, r *http.Request, wishlistId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удаление элемента из вишлиста
// (DELETE /wishlists/{wishlistId}/items/{itemId})
func (_ Unimplemented) DeleteWishlistItem(w http.ResponseWriter, r *http.Request, wishlistId int64, itemId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetWishlists operation middleware
func (siw *ServerInterfaceWrapper) GetWishlists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWishlists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWishlist operation middleware
func (siw *ServerInterfaceWrapper) CreateWishlist(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWishlist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWishlist operation middleware
func (siw *ServerInterfaceWrapper) DeleteWishlist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wishlistId" -------------
	var wishlistId int64

	err = runtime.BindStyledParameterWithOptions("simple", "wishlistId", chi.URLParam(r, "wishlistId"), &wishlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wishlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWishlist(w, r, wishlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWishlistById operation middleware
func (siw *ServerInterfaceWrapper) GetWishlistById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wishlistId" -------------
	var wishlistId int64

	err = runtime.BindStyledParameterWithOptions("simple", "wishlistId", chi.URLParam(r, "wishlistId"), &wishlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wishlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWishlistById(w, r, wishlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddWishlistItem operation middleware
func (siw *ServerInterfaceWrapper) AddWishlistItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wishlistId" -------------
	var wishlistId int64

	err = runtime.BindStyledParameterWithOptions("simple", "wishlistId", chi.URLParam(r, "wishlistId"), &wishlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wishlistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddWishlistItem(w, r, wishlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWishlistItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteWishlistItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "wishlistId" -------------
	var wishlistId int64

	err = runtime.BindStyledParameterWithOptions("simple", "wishlistId", chi.URLParam(r, "wishlistId"), &wishlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wishlistId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId int64

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWishlistItem(w, r, wishlistId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wishlists", wrapper.GetWishlists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/wishlists", wrapper.CreateWishlist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/wishlists/{wishlistId}", wrapper.DeleteWishlist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wishlists/{wishlistId}", wrapper.GetWishlistById)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/wishlists/{wishlistId}/items", wrapper.AddWishlistItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/wishlists/{wishlistId}/items/{itemId}", wrapper.DeleteWishlistItem)
	})

	return r
}
